import React, { useState } from 'react';
import { useBudgetStore } from '../stores/budgetStore';
import { useTransactionStore } from '../stores/transactionStore';
export const BudgetsPage = () => {
  const { budgets, addBudget } = useBudgetStore();
  const { transactions } = useTransactionStore();
  const [show, setShow] = useState(false);
  const [form, setForm] = useState({ category: '', amount: 0 });
  const currentMonth = new Date().toISOString().slice(0,7);
  const getSpent = (cat) => transactions.filter(t=>t.type==='expense' && t.category===cat && t.date.startsWith(currentMonth)).reduce((s,t)=>s+t.amount,0);
  const submit = (e) => { e.preventDefault(); if(form.category && form.amount>0){ addBudget({ ...form, month: currentMonth }); setForm({ category: '', amount: 0 }); setShow(false); } };
  return <div className="p-6"><div className="flex justify-between mb-6"><h1 className="text-2xl font-bold">Budgets</h1><button onClick={()=>setShow(true)} className="bg-blue-600 text-white px-4 py-2 rounded-lg">+ New</button></div><div className="grid gap-4">{budgets.filter(b=>b.month===currentMonth).map(b=>{ const spent = getSpent(b.category); const pct = Math.min(100, (spent/b.amount)*100); return <div key={b.id} className="bg-white rounded-xl shadow p-4"><div className="flex justify-between"><div><h3 className="font-bold">{b.category}</h3><p className="text-sm text-gray-500">Budget: Rp {b.amount.toLocaleString()}</p></div><div className="text-right"><p className="text-sm">Spent: Rp {spent.toLocaleString()}</p><p className={`text-sm ${b.amount-spent>=0?'text-green-600':'text-red-600'}`}>Remaining: Rp {(b.amount-spent).toLocaleString()}</p></div></div><div className="h-2 bg-gray-200 rounded-full mt-2 overflow-hidden"><div className={`h-full rounded-full ${pct>=100?'bg-red-500':pct>=80?'bg-yellow-500':'bg-green-500'}`} style={{width:`${pct}%`}}></div></div></div>;})}</div>{show && <div className="fixed inset-0 bg-black/50 flex items-center justify-center"><div className="bg-white rounded-xl p-6 w-96"><h2 className="text-xl font-bold mb-4">New Budget</h2><form onSubmit={submit}><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="w-full p-3 border rounded-lg mb-3" required><option value="">Select category</option><option value="Food">Food</option><option value="Transport">Transport</option><option value="Shopping">Shopping</option><option value="Bills">Bills</option><option value="Entertainment">Entertainment</option></select><input type="number" placeholder="Budget Amount" value={form.amount} onChange={e=>setForm({...form,amount:parseFloat(e.target.value)||0})} className="w-full p-3 border rounded-lg mb-4" required /><div className="flex gap-3"><button type="button" onClick={()=>setShow(false)} className="flex-1 border rounded-lg p-2">Cancel</button><button type="submit" className="flex-1 bg-blue-600 text-white rounded-lg p-2">Save</button></div></form></div></div>}</div>;
};