import React, { useState } from 'react';
import { useGoalStore } from '../stores/goalStore';
export const GoalsPage = () => {
  const { goals, addGoal, contribute, deleteGoal } = useGoalStore();
  const [showSheet, setShowSheet] = useState(false);
  const [showContribute, setShowContribute] = useState(null);
  const [amount, setAmount] = useState(0);
  const [form, setForm] = useState({ name: '', target: 0 });
  const handleSubmit = (e) => { e.preventDefault(); if(form.name && form.target){ addGoal(form); setForm({ name: '', target: 0 }); setShowSheet(false); } };
  const doContribute = () => { if(showContribute && amount>0){ contribute(showContribute.id, amount); setShowContribute(null); setAmount(0); } };
  return (<><div className="flex-between mb-4"><h1 className="text-title-large">Goals</h1><button onClick={() => setShowSheet(true)} className="btn-primary" style={{ width: 'auto', padding: '8px 16px' }}>+ Tambah</button></div>{goals.map(g => { const pct = Math.min(100, (g.current/g.target)*100); return <div key={g.id} className="card mb-2"><div className="flex-between"><span className="text-title-medium">{g.name}</span><span className="text-headline text-success">{pct.toFixed(0)}%</span></div><div className="progress-bar"><div className="progress-fill progress-fill-success" style={{width: `${pct}%`}}></div></div><div className="flex-between mt-1"><span className="text-label">Rp {g.current.toLocaleString()} / Rp {g.target.toLocaleString()}</span><div><button onClick={() => setShowContribute(g)} className="text-primary mr-2"><i className="ti ti-plus"></i></button><button onClick={() => deleteGoal(g.id)} className="text-error"><i className="ti ti-trash"></i></button></div></div></div>;})}{showSheet && <div className="sheet-overlay" onClick={() => setShowSheet(false)}><div className="sheet" onClick={e => e.stopPropagation()}><div className="sheet-handle"></div><h2 className="text-title-medium mb-4">Tambah Goal</h2><form onSubmit={handleSubmit}><input type="text" placeholder="Nama Goal" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="input-field w-full mb-3" required /><input type="number" placeholder="Target Amount" value={form.target} onChange={e=>setForm({...form,target:parseFloat(e.target.value)||0})} className="input-field w-full mb-4" required /><div className="flex gap-2"><button type="button" onClick={()=>setShowSheet(false)} className="btn-outline">Batal</button><button type="submit" className="btn-primary">Simpan</button></div></form></div></div>}{showContribute && <div className="sheet-overlay" onClick={() => setShowContribute(null)}><div className="sheet" onClick={e => e.stopPropagation()}><div className="sheet-handle"></div><h2 className="text-title-medium mb-2">Kontribusi ke {showContribute.name}</h2><p className="text-label mb-4">Current: Rp {showContribute.current.toLocaleString()} / Rp {showContribute.target.toLocaleString()}</p><input type="number" placeholder="Jumlah" value={amount} onChange={e=>setAmount(parseFloat(e.target.value)||0)} className="input-field w-full mb-4" /><div className="flex gap-2"><button onClick={()=>setShowContribute(null)} className="btn-outline">Batal</button><button onClick={doContribute} className="btn-primary">Tambah</button></div></div></div>}</>);
};
