import React, { useState } from 'react';
import { useGoalStore } from '../stores/goalStore';
export const GoalsPage = () => {
  const { goals, addGoal, contribute } = useGoalStore();
  const [show, setShow] = useState(false);
  const [showContribute, setShowContribute] = useState(null);
  const [amount, setAmount] = useState(0);
  const [form, setForm] = useState({ name: '', target: 0 });
  const submit = (e) => { e.preventDefault(); if(form.name && form.target>0){ addGoal(form); setForm({ name: '', target: 0 }); setShow(false); } };
  const doContribute = () => { if(showContribute && amount>0){ contribute(showContribute.id, amount); setShowContribute(null); setAmount(0); } };
  return <div className="p-6"><div className="flex justify-between mb-6"><h1 className="text-2xl font-bold">Goals</h1><button onClick={()=>setShow(true)} className="bg-blue-600 text-white px-4 py-2 rounded-lg">+ New</button></div><div className="grid gap-4">{goals.map(g=>{ const pct = Math.min(100, (g.current/g.target)*100); return <div key={g.id} className="bg-white rounded-xl shadow p-4"><div className="flex justify-between"><div><h3 className="font-bold">{g.name}</h3><p className="text-sm text-gray-500">Rp {g.current.toLocaleString()} / Rp {g.target.toLocaleString()}</p></div><div className="text-2xl font-bold text-green-600">{pct.toFixed(0)}%</div></div><div className="h-2 bg-gray-200 rounded-full mt-2 mb-3 overflow-hidden"><div className="h-full bg-green-500 rounded-full" style={{width:`${pct}%`}}></div></div><button onClick={()=>setShowContribute(g)} className="w-full bg-green-600 text-white py-2 rounded-lg">Contribute</button></div>;})}</div>{show && <div className="fixed inset-0 bg-black/50 flex items-center justify-center"><div className="bg-white rounded-xl p-6 w-96"><h2 className="text-xl font-bold mb-4">New Goal</h2><form onSubmit={submit}><input type="text" placeholder="Goal name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="w-full p-3 border rounded-lg mb-3" required /><input type="number" placeholder="Target amount" value={form.target} onChange={e=>setForm({...form,target:parseFloat(e.target.value)||0})} className="w-full p-3 border rounded-lg mb-4" required /><div className="flex gap-3"><button type="button" onClick={()=>setShow(false)} className="flex-1 border rounded-lg p-2">Cancel</button><button type="submit" className="flex-1 bg-blue-600 text-white rounded-lg p-2">Save</button></div></form></div></div>}{showContribute && <div className="fixed inset-0 bg-black/50 flex items-center justify-center"><div className="bg-white rounded-xl p-6 w-96"><h2 className="text-xl font-bold mb-2">Contribute to {showContribute.name}</h2><p className="text-gray-500 mb-4">Current: Rp {showContribute.current.toLocaleString()} / Rp {showContribute.target.toLocaleString()}</p><input type="number" placeholder="Amount" value={amount} onChange={e=>setAmount(parseFloat(e.target.value)||0)} className="w-full p-3 border rounded-lg mb-4" /><div className="flex gap-3"><button onClick={()=>setShowContribute(null)} className="flex-1 border rounded-lg p-2">Cancel</button><button onClick={doContribute} className="flex-1 bg-green-600 text-white rounded-lg p-2">Add</button></div></div></div>}</div>;
};