import React, { useState } from 'react';
import { useTransactionStore } from '../stores/transactionStore';
import { useWalletStore } from '../stores/walletStore';
export const TransactionsPage = () => {
  const { transactions, addTransaction, deleteTransaction } = useTransactionStore();
  const { wallets, updateBalance } = useWalletStore();
  const [showSheet, setShowSheet] = useState(false);
  const [form, setForm] = useState({ walletId: wallets[0]?.id || '', amount: 0, type: 'expense', category: '', desc: '', date: new Date().toISOString().slice(0,10) });
  const categories = { income: ['Salary', 'Freelance', 'Gift'], expense: ['Food', 'Transport', 'Shopping', 'Bills', 'Entertainment'] };
  const handleSubmit = (e) => { e.preventDefault(); const amount = form.type === 'expense' ? -form.amount : form.amount; addTransaction(form); updateBalance(form.walletId, amount); setShowSheet(false); setForm({ walletId: wallets[0]?.id, amount: 0, type: 'expense', category: '', desc: '', date: new Date().toISOString().slice(0,10) }); };
  const getWalletName = (id) => wallets.find(w => w.id === id)?.name || 'Unknown';
  return (<><div className="flex-between mb-4"><h1 className="text-title-large">Transaksi</h1><button onClick={() => setShowSheet(true)} className="btn-primary" style={{ width: 'auto', padding: '8px 16px' }}>+ Tambah</button></div>{transactions.map(tx => <div key={tx.id} className="card mb-2"><div className="flex-between"><div><div className="text-title-medium">{tx.desc}</div><div className="text-label">{tx.category} • {getWalletName(tx.walletId)} • {tx.date}</div></div><div className="text-right"><span className={`text-title-medium ${tx.type === 'income' ? 'text-success' : 'text-error'}`}>{tx.type === 'income' ? '+' : '-'}Rp {tx.amount.toLocaleString()}</span><button onClick={() => deleteTransaction(tx.id)} className="text-error ml-2"><i className="ti ti-trash"></i></button></div></div></div>)}{showSheet && <div className="sheet-overlay" onClick={() => setShowSheet(false)}><div className="sheet" onClick={e => e.stopPropagation()}><div className="sheet-handle"></div><h2 className="text-title-medium mb-4">Tambah Transaksi</h2><form onSubmit={handleSubmit}><select value={form.type} onChange={e=>setForm({...form,type:e.target.value,category:''})} className="input-field w-full mb-3"><option value="expense">Expense</option><option value="income">Income</option></select><select value={form.walletId} onChange={e=>setForm({...form,walletId:e.target.value})} className="input-field w-full mb-3">{wallets.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="input-field w-full mb-3" required><option value="">Kategori</option>{categories[form.type].map(c=><option key={c}>{c}</option>)}</select><input type="text" placeholder="Deskripsi" value={form.desc} onChange={e=>setForm({...form,desc:e.target.value})} className="input-field w-full mb-3" required /><input type="number" placeholder="Jumlah" value={form.amount} onChange={e=>setForm({...form,amount:parseFloat(e.target.value)||0})} className="input-field w-full mb-3" required /><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className="input-field w-full mb-4" required /><div className="flex gap-2"><button type="button" onClick={()=>setShowSheet(false)} className="btn-outline">Batal</button><button type="submit" className="btn-primary">Simpan</button></div></form></div></div>}</>);
};
