import React, { useState } from 'react';
import { useTransactionStore } from '../stores/transactionStore';
import { useWalletStore } from '../stores/walletStore';
import { useBudgetStore } from '../stores/budgetStore';
export const TransactionsPage = () => {
  const { transactions, addTransaction, deleteTransaction } = useTransactionStore();
  const { wallets, updateBalance } = useWalletStore();
  const { updateSpent } = useBudgetStore();
  const [show, setShow] = useState(false);
  const [form, setForm] = useState({ walletId: wallets[0]?.id || '', amount: 0, type: 'expense', category: '', desc: '', date: new Date().toISOString().slice(0,10) });
  const submit = (e) => { e.preventDefault(); const amt = form.type === 'expense' ? -form.amount : form.amount; addTransaction(form); updateBalance(form.walletId, amt); if(form.type==='expense') updateSpent(form.category, form.amount); setShow(false); setForm({ walletId: wallets[0]?.id, amount:0, type:'expense', category:'', desc:'', date:new Date().toISOString().slice(0,10) }); };
  const categories = { income: ['Salary', 'Freelance', 'Gift'], expense: ['Food', 'Transport', 'Shopping', 'Bills', 'Entertainment'] };
  return <div className="p-6"><div className="flex justify-between mb-6"><h1 className="text-2xl font-bold">Transactions</h1><button onClick={()=>setShow(true)} className="bg-blue-600 text-white px-4 py-2 rounded-lg">+ Add</button></div><div className="bg-white rounded-xl shadow">{transactions.map(t=><div key={t.id} className="p-4 border-b flex justify-between"><div><div className="font-medium">{t.desc}</div><div className="text-sm text-gray-500">{t.category} • {t.date}</div></div><div className="flex gap-3 items-center"><span className={`font-semibold ${t.type==='income'?'text-green-600':'text-red-600'}`}>{t.type==='income'?'+':'-'}Rp {t.amount.toLocaleString()}</span><button onClick={()=>deleteTransaction(t.id)} className="text-red-500">🗑️</button></div></div>)}</div>{show && <div className="fixed inset-0 bg-black/50 flex items-center justify-center p-4 overflow-y-auto"><div className="bg-white rounded-xl p-6 w-full max-w-md"><h2 className="text-xl font-bold mb-4">Add Transaction</h2><form onSubmit={submit}><select value={form.walletId} onChange={e=>setForm({...form,walletId:e.target.value})} className="w-full p-3 border rounded-lg mb-3">{wallets.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><select value={form.type} onChange={e=>setForm({...form,type:e.target.value,category:''})} className="w-full p-3 border rounded-lg mb-3"><option value="expense">Expense</option><option value="income">Income</option></select><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="w-full p-3 border rounded-lg mb-3" required><option value="">Select category</option>{categories[form.type].map(c=><option key={c} value={c}>{c}</option>)}</select><input type="text" placeholder="Description" value={form.desc} onChange={e=>setForm({...form,desc:e.target.value})} className="w-full p-3 border rounded-lg mb-3" required /><input type="number" placeholder="Amount" value={form.amount} onChange={e=>setForm({...form,amount:parseFloat(e.target.value)||0})} className="w-full p-3 border rounded-lg mb-3" required /><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className="w-full p-3 border rounded-lg mb-4" required /><div className="flex gap-3"><button type="button" onClick={()=>setShow(false)} className="flex-1 border rounded-lg p-2">Cancel</button><button type="submit" className="flex-1 bg-blue-600 text-white rounded-lg p-2">Save</button></div></form></div></div>}</div>;
};